# Generated by Django 3.2.6 on 2021-10-02 17:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=30)),
                ('startup_date', models.DateTimeField()),
                ('heartbeat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_name', models.CharField(max_length=30)),
                ('input_value', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)])),
                ('input_type', models.CharField(choices=[('S', 'Switch'), ('B', 'Button'), ('R', 'Range')], max_length=1)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlCenter.devices')),
            ],
        ),
    ]
