# Generated by Django 3.2.7 on 2021-10-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlCenter', '0002_rename_action_actions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actions',
            options={'managed': True, 'verbose_name': 'Action', 'verbose_name_plural': 'Actions'},
        ),
        migrations.AlterModelOptions(
            name='devices',
            options={'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.AddField(
            model_name='actions',
            name='input_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='actions',
            table='',
        ),
    ]
