# Generated by Django 3.2.6 on 2021-11-01 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlCenter', '0003_auto_20211003_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actions',
            old_name='device',
            new_name='device_id',
        ),
    ]
