# Generated by Django 3.2.6 on 2021-11-01 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('controlCenter', '0004_rename_device_actions_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='heartbeat',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='devices',
            name='startup_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
