# Generated by Django 3.2.6 on 2021-11-01 15:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('controlCenter', '0005_auto_20211101_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='startup_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 15, 17, 44, 802401, tzinfo=utc)),
        ),
    ]
