# Generated by Django 3.2.6 on 2021-11-01 15:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('controlCenter', '0006_alter_devices_startup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='startup_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 15, 39, 56, 931712, tzinfo=utc)),
        ),
    ]
